export const DEMAND_CATEGORY_CREATE_REQUEST = 'DEMAND_CATEGORY_CREATE_REQUEST';
export const DEMAND_CATEGORY_CREATE_SUCCESS = 'DEMAND_CATEGORY_CREATE_SUCCESS';
export const DEMAND_CATEGORY_CREATE_FAIL = 'DEMAND_CATEGORY_CREATE_FAIL';

export const DEMAND_CATEGORY_DETAILS_REQUEST = 'DEMAND_CATEGORY_DETAILS_REQUEST';
export const DEMAND_CATEGORY_DETAILS_SUCCESS = 'DEMAND_CATEGORY_DETAILS_SUCCESS';
export const DEMAND_CATEGORY_DETAILS_FAIL = 'DEMAND_CATEGORY_DETAILS_FAIL';
export const DEMAND_CATEGORY_DETAILS_RESET = 'DEMAND_CATEGORY_DETAILS_RESET';


export const DEMAND_CATEGORY_DETAILS_REVENUE_REQUEST = 'DEMAND_CATEGORY_DETAILS_REVENUE_REQUEST';
export const DEMAND_CATEGORY_DETAILS_REVENUE_SUCCESS = 'DEMAND_CATEGORY_DETAILS_REVENUE_SUCCESS';
export const DEMAND_CATEGORY_DETAILS_REVENUE_FAIL = 'DEMAND_CATEGORY_DETAILS_REVENUE_FAIL';
export const DEMAND_CATEGORY_DETAILS_REVENUE_RESET = 'DEMAND_CATEGORY_DETAILS_REVENUE_RESET';

export const DEMAND_CATEGORY_UPDATE_REQUEST = 'DEMAND_CATEGORY_UPDATE_REQUEST';
export const DEMAND_CATEGORY_UPDATE_SUCCESS = 'DEMAND_CATEGORY_UPDATE_SUCCESS';
export const DEMAND_CATEGORY_UPDATE_FAIL = 'DEMAND_CATEGORY_UPDATE_FAIL';
export const DEMAND_CATEGORY_UPDATE_RESET = 'DEMAND_CATEGORY_UPDATE_RESET';